server.port=8082
spring.application.name=JobSeeker

eureka.instance.client.serviceUrl.defaultZone=http://localhost:8761
spring.zipkin.base-url=http://localhost:9411
management.tracing.sample.probability=1.0


resilience4j.circuitbreaker.configurations=JobSeeker
resilience4j.circuitbreaker.instances.JobSeeker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.JobSeeker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.JobSeeker.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.JobSeeker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.JobSeeker.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.JobSeeker.waitDurationInOpenState=3s
resilience4j.circuitbreaker.instances.JobSeeker.slowCallRateThreshold=30
resilience4j.circuitbreaker.instances.JobSeeker.slowCallDurationThreshold=10
resilience4j.circuitbreaker.instances.JobSeeker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.JobSeeker.registerHealthIndicator=true

management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always

# Log Levels
#TRACE < DEBUG < INFO < WARN < ERROR
#logging.level.org.springframework=ERROR
#logging.level.com.jade=TRACE
logging.level.root=INFO
#logging.file.name=jade-app.log
logging.file.path=D:/demo/jadelogs

